{% set data = load_setup_py_data() %}
# must do conda install -c NostrumBioDiscovery pele_platform
package:
  name: pele_platform
  version: {{ data.get('version') }}

about:
  home: https://github.com/AlbertCS/pele_platform
  license: Apache
  license_file: LICENSE
  summary: Automatic platform to spawn PELE, AdaptivePELE, MSM_PELE, frag_PELE jobs and Satumut/Plurizymer

source:
  path: ../../

build:
  script: python -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    # Base dependencies
    - python
    - numpy
    - matplotlib
    - scipy
    - biopython
    - cython
    - pandas==1.2.3
    - pytest
    - adaptive_pele==1.7.1
    - ploprottemp==1.0.1
    - pyyaml
    - pillow
    - fpdf
    - scikit-learn>0.20
    - rdkit
    - frag_pele==3.1.1
    - pppele==1.0.8
    - peleffy==1.4.1
    #- drug_learning not ready yet
    - hdbscan==0.8.27
    - mdtraj==1.9.5
    - seaborn
    - satumut
    - pyparsing==2.4.7
    - tqdm

test:
  imports:
    - pele_platform
  command:
    - python -m pele_platform.main -h
